### ISSUE TITLE
访问“浙江新闻”，插件自动拉伸

### ISSUE THREAD

**Issue by Luoxiaopan** [YGYOOO/ajax-interceptor#1]
网址：https://zj.zjol.com.cn/news.html?id=1176316&from=timeline&isappinstalled=0
错误效果：
![image](https://user-images.githubusercontent.com/10296844/55928231-904fe080-5c4a-11e9-844e-42632d906fc5.png)
![image](https://user-images.githubusercontent.com/10296844/55928246-a067c000-5c4a-11e9-9ace-0cdde11dba6b.png)

**Comment by YGYOOO** [comment]
感谢提出，看了下是浙江新闻的样式覆盖了我这个插件iframe的样式，0.5版本会修复，预计下周更新完成（审核需要4、5天）。你可以先在chrome://extensions里把该插件关闭。

**Comment by YGYOOO** [comment]
0.5版本更新了，确认插件版本已经更新到0.5后，重新进入浙江新闻页面，应该不会有该问题了

**Comment by brickswong7** [comment]
![image](https://user-images.githubusercontent.com/20966000/63327958-d425c580-c361-11e9-8898-f7a7a25c7d49.png)
http://localhost:8000 开发，为什么调用接口会出现这种情况
