### ISSUE TITLE
在Quick BI 中，inputUrl.trim() 报错

### ISSUE THREAD

**Issue by rideWind97** [YGYOOO/ajax-interceptor#106]
getCompleteUrl中的inputUrl的类型没有定义好，有时候是一个对象

此时 inputUrl.trim() 会报错

![image](https://github.com/YGYOOO/ajax-interceptor/assets/47934820/5074a788-5d46-4cfd-a092-d4d5d326c36d)

所以在调用之前，必须保证 inputUrl 是一个字符串

调用方法之前的逻辑
![image](https://github.com/YGYOOO/ajax-interceptor/assets/47934820/1babd5e7-a475-4771-bf83-d5762a83fe1f)

此处应确保 inputUrl 是 字符串

所以应该如图修改
![image](https://github.com/YGYOOO/ajax-interceptor/assets/47934820/b04ae743-892e-40a7-983c-a120eafa0500)

**Comment by rideWind97** [comment]
我提交了一个pr
https://github.com/YGYOOO/ajax-interceptor/pull/107

**Comment by YGYOOO** [comment]
感谢，已merge，已提交chrome商店审核，预计一周内通过
