### ISSUE TITLE
myFetch入参只有一个，导致请求没有走到逻辑条件

### ISSUE THREAD

**Issue by xiaohesong** [YGYOOO/ajax-interceptor#112]
myFetch的args出现了下面的情况：
参数只有一个Request对象
![image](https://github.com/YGYOOO/ajax-interceptor/assets/12555626/fe2e7c56-2c3d-4421-9067-51c93be19d6b)

这就导致没有走到对应的逻辑，导致插件不工作的问题。

然后 [提了个PR](https://github.com/YGYOOO/ajax-interceptor/pull/111)

**Comment by YGYOOO** [comment]
你好哈，看了下你提的pr，文字描述比较少，我们对齐一下哈，看看我有没有理解错。
从代码上看我理解是做了两件事，一是修复一个bug，就是fetch第一个参数是object时，第二个参数会为空，此时data.body当然取不到，应该取args[0].body；二是针对body为readableStream的情况，先转为string，然后用户可以在专业模式里操作，然后再重新转成readableStream，我理解这个步骤目的是方便用户在专业模式里直接改body值？但不是必须的吧

**Comment by xiaohesong** [comment]
感谢回复。
1. 是的
2. 读取readable流是为了方便使用方处理body，降低接入上手成本。如果不需要，去掉也行。

**Comment by fengwuxiao** [comment]
![image](https://github.com/YGYOOO/ajax-interceptor/assets/24424751/7ce0ca33-444c-424b-b200-eaf79ef072f9)
只有一个参数，data undefined 导致报错

**Comment by xiaohesong** [comment]
> ![image](https://private-user-images.githubusercontent.com/24424751/338447697-7ce0ca33-444c-424b-b200-eaf79ef072f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODYzNTQsIm5iZiI6MTcxODA4NjA1NCwicGF0aCI6Ii8yNDQyNDc1MS8zMzg0NDc2OTctN2NlMGNhMzMtNDQ0Yy00MjRiLWIyMDAtZWFmNzllZjA3MmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA2MDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZDIyOGRhZDVkZWM0OGE5YmMyMzhiYTQ5MGJkY2JjZjU3ZTcxMGFlNzZkNmYxNDIxMTNjNjY5ZGE0YjNjODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b6uk5XBIIQkWVPR574iXWXsVsQIF-WpHck-JP5RA7e4) 只有一个参数，data undefined 导致报错

应该是get请求吧 我改下 上个PR带出来的问题。

**Comment by YGYOOO** [comment]
https://github.com/YGYOOO/ajax-interceptor/issues/114 话说更新的代码会导致这个问题么（感觉应该不会吧，不相干呀，react热更新是基于websocket做的吧

**Comment by xiaohesong** [comment]
讲道理应该不会

> #114 话说更新的代码会导致这个问题么（感觉应该不会吧，不相干呀，react热更新是基于websocket做的吧

应该是因为这个PR导致的 🤣，试了下，https://github.com/YGYOOO/ajax-interceptor/pull/113 这里的代码加上去，就可以正常热更新

为啥插件导致热更新失败，也不太理解，大致查了下可能的原因： 
1. 未捕获的js错误，可能影响到Webpack Dev Server 注入的 HMR代码(hmr的具体运行逻辑不太清楚)；
2. 可能是加载的顺序

**Comment by YGYOOO** [comment]
噢噢，有可能，晚上我更新下，感谢哈~

**Comment by xiaohesong** [comment]
> 噢噢，有可能，晚上我更新下，感谢哈~

好的 惭愧 带出来的问题  😅

**Comment by YGYOOO** [comment]
> > 噢噢，有可能，晚上我更新下，感谢哈~
> 
> 好的 惭愧 带出来的问题 😅

 哈哈没事没事，你还修了我们之前的问题呢
