### ISSUE TITLE
1.5.7版本拦截请求失效，控制台报错

### ISSUE THREAD

**Issue by somertang** [YGYOOO/ajax-interceptor#116]
您好，我近期使用 ajax modifier(1.5.7) 发现无法成功修改请求返回内容，并且浏览器控制台显示了报错信息。
![CleanShot 2024-06-18 at 10 41 41](https://github.com/YGYOOO/ajax-interceptor/assets/30136420/b98d6cba-29dd-4326-af74-751e8069193c)
![CleanShot 2024-06-18 at 10 42 07](https://github.com/YGYOOO/ajax-interceptor/assets/30136420/917b53f5-d6c3-472a-b748-a7ffadc7b25e)

**Comment by dafengxiang** [comment]
我这里也是，哭死

**Comment by YGYOOO** [comment]
不好意思，稍等我更新1.5.8

**Comment by YGYOOO** [comment]
已更新1.5.8，再看看呢

**Comment by somertang** [comment]
> 已更新1.5.8，再看看呢

感谢，更新到 1.5.8 已成功解决问题
![CleanShot 2024-06-18 at 22 13 35](https://github.com/YGYOOO/ajax-interceptor/assets/30136420/d7dd99ce-50f9-4d84-bf23-8017d7fd81b5)
