### ISSUE TITLE
有个页面插件会自动弹出，占用空间影响浏览

### ISSUE THREAD

**Issue by z-jingjie** [YGYOOO/ajax-interceptor#12]
https://litmus.com/ebooks/state-of-email-workflows-2018
![Untitled](https://user-images.githubusercontent.com/9072130/71348906-91daf200-25a8-11ea-9b07-13dd81087483.jpg)

**Comment by YGYOOO** [comment]
你好，刚提交了0.8版本修复了该bug，但正在审核，预计几天内生效

**Comment by z-jingjie** [comment]
今天遇到另一个页面：
https://pilot.search.dell.com/developer
![dssasdjt5e45yet35werg](https://user-images.githubusercontent.com/9072130/83370262-74c90b80-a3f1-11ea-8262-e1340f08f9f0.jpg)
