### ISSUE TITLE
请教下重写 fetch 是为何要bind(window)?

### ISSUE THREAD

**Issue by 03128crz** [YGYOOO/ajax-interceptor#16]
originalFetch: window.fetch.bind(window)
为何不能像XMLHttpRequest一样：
originalXHR: window.XMLHttpRequest,

**Comment by YGYOOO** [comment]
因为XMLHttpRequest是new了以后使用的，而fetch是直接作为函数使用的，所以保险起见bind了一下window，没啥特殊意义，你去掉应该也一样

**Comment by 03128crz** [comment]
> 因为XMLHttpRequest是new了以后使用的，而fetch是直接作为函数使用的，所以保险起见bind了一下window，没啥特殊意义，你去掉应该也一样

好的，谢谢，再请教下在MyFetch中如果想console.log(替换前的返回数据) 应该要怎么弄
`
myFetch: function(...args) {
    return ajax_interceptor_qoweifjqon.originalFetch(...args).then((response) => {
      let txt = undefined;
      ajax_interceptor_qoweifjqon.settings.ajaxInterceptor_rules.forEach(({match, overrideTxt = ''}) => {
        if (match && response.url.indexOf(match) > -1) {
          window.dispatchEvent(new CustomEvent("pageScript", {
            detail: {url: response.url, match}
          }));
          txt = overrideTxt;
        }
      });
`

**Comment by YGYOOO** [comment]
不是有response对象么，response.json().then(data => console.log(data))这样就行了

**Comment by 03128crz** [comment]
> 不是有response对象么，response.json().then(data => console.log(data))这样就行了
我一开始也是这样想的，不过测试后会报错
```
myFetch: function (...args) {
    return ajax_interceptor_qoweifjqon.originalFetch(...args).then((response) => {
      response.json().then(data=>{
        console.log(data);
      });
     ..........
     ...........

      return response;
    });
  },
```
![image](https://user-images.githubusercontent.com/3424553/79532200-016c7400-80a7-11ea-933b-abb587d10a1c.png)

**Comment by YGYOOO** [comment]
试下这样response.clone().json().then(data => console.log(data))，还不行试下把json改成text
