### ISSUE TITLE
可以提个建议吗：在开发者工具中添加一个panel

### ISSUE THREAD

**Issue by meteor199** [YGYOOO/ajax-interceptor#19]
可以在dev tools中加个panel吗，就像 vue dev tools一样。
这个panel可以模拟 开发者工具里面的network

- 显示所有连接，当被修改后，可以显示修改后的连接。像network一样有request,response等
- 右击某个连接可以添加拦截。会弹出一个对话框，设置拦截规则。
- 假如当前连接被拦截，则添加一个标签或高亮显示。
- 提供一个按键，点击后弹窗或其他方式显示所有拦截，并可以修改。

**Comment by YGYOOO** [comment]
以后可以考虑，但改造量较大，近期先不考虑

**Comment by YGYOOO** [comment]
![image](https://github.com/YGYOOO/ajax-interceptor/assets/15754991/f3ae4ac7-d32e-45e5-bfba-74f5cc72688d)
已支持devtools
