### ISSUE TITLE
chrome商店找不到，链接404

### ISSUE THREAD

**Issue by lzwzzy** [YGYOOO/ajax-interceptor#2]
chrome商店找不到，链接404
![image](https://user-images.githubusercontent.com/23731957/56454829-36a58f80-6389-11e9-8b71-7a3dbcd8a807.png)

**Comment by YGYOOO** [comment]
不好意思，之前手抖下架了，现在重新发布了，请再确认下

**Comment by lzwzzy** [comment]
这个是不可以真正拦截请求并返回的吧

**Comment by YGYOOO** [comment]
从网络层面上看没有进行任何“拦截”，但是从js层面上看是“拦截”了，实际上就是（在你获取到返回值之前）修改了fetch方法或XMLHTTPRequest对象里的返回值。
