### ISSUE TITLE
json editor 无法修改为int类型的数据

### ISSUE THREAD

**Issue by sunshinev** [YGYOOO/ajax-interceptor#23]
编辑之前
![image](https://user-images.githubusercontent.com/8537718/86223082-ad5b3100-bbb9-11ea-9ebc-ed988f8c9f09.png)

编辑之后
![image](https://user-images.githubusercontent.com/8537718/86223113-b64c0280-bbb9-11ea-9280-6018744e99cc.png)

**Comment by YGYOOO** [comment]
![image](https://user-images.githubusercontent.com/15754991/87024148-52ee5000-c20b-11ea-8cc1-230c22dd374a.png)
你好，需要数字类型的话请点这个按钮
