### ISSUE TITLE
您好！我想问一下，这个可以用于okex 最新的ieo项目吗？

### ISSUE THREAD

**Issue by FAKER-A** [YGYOOO/ajax-interceptor#3]

**Comment by YGYOOO** [comment]
您好，我不太了解okex、ieo是啥。。。是要怎么用于它呢？这个不就是个chrome插件么

**Comment by FAKER-A** [comment]
> 您好，我不太了解okex、ieo是啥。。。是要怎么用于它呢？这个不就是个chrome插件么

不好意思，应该是别人拿你的插件做的教程。打扰了！
