### ISSUE TITLE
修改了接口返回值没生效

### ISSUE THREAD

**Issue by tuihou123321** [YGYOOO/ajax-interceptor#38]
测试地址：https://juejin.cn/user/2189882895108616/posts?sort=newest
接口地址：https://api.juejin.cn/content_api/v1/article/query_list
已经重启浏览器和刷新页面，但是返回的接口内容没有改变，并且页面一直在loading阶段

![image](https://user-images.githubusercontent.com/7146036/113682247-8526d280-96f5-11eb-95cf-c16554ed8e36.png)

**Comment by tuihou123321** [comment]
chrome版本 89.0.4389.114（正式版本） （64 位）
Ajax Interceptor 版本  0.9

**Comment by Jcanno** [comment]
> chrome版本 89.0.4389.114（正式版本） （64 位）
> Ajax Interceptor 版本 0.9

我也是没生效😭

**Comment by YGYOOO** [comment]
你好，感谢提出此问题，排查后是中文字符编码问题，目前已在1.0版本中修复，正在审核中，你也可以将该github仓库拉至本地，进入chrome://extensions/，打开开发者模式，点击“加载已解压的扩展程序”加载该github仓库，查看是否生效
