### ISSUE TITLE
目前插件好像不起作用

### ISSUE THREAD

**Issue by Jcanno** [YGYOOO/ajax-interceptor#39]
chrome 89版本
即使更改了原页面的ajax对象，也不能更改响应结果，不知作者可否看一下

**Comment by YGYOOO** [comment]
你好，感谢提出此问题，排查后是中文字符编码问题，目前已在1.0版本中修复，正在审核中，你也可以将该github仓库拉至本地，进入chrome://extensions/，打开开发者模式，点击“加载已解压的扩展程序”加载该github仓库，查看是否生效

**Comment by Jcanno** [comment]
> 你好，感谢提出此问题，排查后是中文字符编码问题，目前已在刚发布的1.0版本中修复

好的，我用最新代码是可以生效了
