### ISSUE TITLE
请问---请求接口的url被篡改，怎么破？

### ISSUE THREAD

**Issue by brickswong7** [YGYOOO/ajax-interceptor#4]
http://localhost:8000开发
![image](https://user-images.githubusercontent.com/20966000/63328114-22d35f80-c362-11e9-80a8-8d26feb37782.png)

**Comment by YGYOOO** [comment]
这个跟ajax-interceptor这个插件应该没啥关系的，你可以在chrome扩展程序页面关掉ajax-interceptor试试，如果还是这样就是你代码本身的问题
