### ISSUE TITLE
有个疑问, 为何注入的iframe也能访问到chrome.storage

### ISSUE THREAD

**Issue by chess99** [YGYOOO/ajax-interceptor#5]
https://github.com/YGYOOO/ajax-interceptor/blob/5d3bf58c52b71824b2565629b3a93c4d9e5c75a2/iframe/index.js#L11

**Comment by YGYOOO** [comment]
这个我也是试了才发现可以的。。。你也可以试下

**Comment by chess99** [comment]
试了下, iframe的域是`chrome-extension://xxxxxx`, 权限和background, popup一样
