### ISSUE TITLE
数组元素（对象）复制后希望能够添加到数组中

### ISSUE THREAD

**Issue by Esa-i** [YGYOOO/ajax-interceptor#54]
![image](https://user-images.githubusercontent.com/23024146/148367239-445d451b-4663-474a-b1cb-6a608e3244a0.png)
期望Item复制后，可以添加到数组pageItemList中
现状：复制后手动添加，对象变成字符串了，不符合预期

**Comment by YGYOOO** [comment]
![image](https://user-images.githubusercontent.com/15754991/148538831-f8a57822-af23-4c11-8f12-c0ade419d239.png)
你好，如上图，粘贴时请点击那个小的确认按钮，那样就会自动执行一次json.parse。点击那个大按钮的话会默认把值当成字符串的
