### ISSUE TITLE
怎么可以和作者联系上，我有一个匹配问题

### ISSUE THREAD

**Issue by limitget** [YGYOOO/ajax-interceptor#58]
https://xxx.com/suppliertender/check?tenantId=1&projectId=1486622125453856770&packageId=&appCode=&purchaseMethod=XJFQ

比如这个地址，我匹配
https://xxx.com/suppliertender/check??tenantId=1&projectId=任意值&packageId=&appCode=&purchaseMethod=XJFQ
这个如何实现，请作者教育

**Comment by YGYOOO** [comment]
<img width="219" alt="image" src="https://user-images.githubusercontent.com/15754991/156285422-b3d37cab-80b2-4f72-a5f2-b3cc3b407948.png">
你好，用正则即可

**Comment by limitget** [comment]
最新的微软游览器无法使用，容易无效

**Comment by YGYOOO** [comment]
> 最新的微软游览器无法使用，容易无效
怀疑是请求时机问题，在该插件加载完成前发起的请求无法被拦截，可以看一下页面加载后触发的请求（比如点击页面上某个按钮触发的请求）是否能被拦截。目前暂未考虑适配edge

**Comment by limitget** [comment]
其实我做了一个比你的方便的，使用golang写的配置好拦截参数直接启动google chrome，检测到自动更改，稳定性会强
