### ISSUE TITLE
能提供个不需要翻墙的安装文件和视频么？

### ISSUE THREAD

**Issue by yalishizhude** [YGYOOO/ajax-interceptor#6]

**Comment by YGYOOO** [comment]
可以先把这个项目拉下来，在chrome://extensions/右上角开启开发者模式，然后左边选择“加载已解压的扩展程序”，选择这个这项目就行。
视频可以看这里：https://weibo.com/5352731024/profile?topnav=1&wvr=6&is_search=1&key_word=ajax&is_all=1#1569291733936

**Comment by YGYOOO** [comment]
https://github.com/YGYOOO/ajax-interceptor/blob/master/Ajax-Interceptor.crx 刚传了下，拖入chrome就可以安装
