### ISSUE TITLE
能拿到request对象吗？ 参数、配置等

### ISSUE THREAD

**Issue by Arima-s** [YGYOOO/ajax-interceptor#65]

**Comment by Arima-s** [comment]
对的对的

**Comment by Arima-s** [comment]
> 是想修改请求体么？

是的是的

**Comment by YGYOOO** [comment]
正好我写过相关油猴脚本，你可以装个油猴，然后建个如下脚本就行（需要你自己修改修改）：
`// ==UserScript==
// @name         hack ajax
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @include      /^.*\.bilibili\..*$/
// @icon         https://www.google.com/s2/favicons?domain=github.com
// @grant        none
// ==/UserScript==

(function() {
// 命名空间
var ajax_interceptor_qoweifjqon = {
  originalXHR: window.XMLHttpRequest,
  myXHR: function() {

    const xhr = new ajax_interceptor_qoweifjqon.originalXHR;

    for (let attr in xhr) {
      if (typeof xhr[attr] === 'function') {
        if (attr === 'open') {
          this.open = function(method, url, ...args) {
            // 这里写你想替换的url
            xhr.open(method, url.replace('contest_code=nova_winter', 'contest_code=testtest'), ...args);
          }
        } else {
          this[attr] = xhr[attr].bind(xhr);
        }
      } else {
        Object.defineProperty(this, attr, {
          get: () => xhr[attr],
          set: (val) => xhr[attr] = val,
          enumerable: true
        });
      }
    }
  },
}

window.XMLHttpRequest = ajax_interceptor_qoweifjqon.myXHR
})();`

这个功能我以后考虑加进插件里
