### ISSUE TITLE
网站/接口加载比较慢的情况下，拦截不到数据

### ISSUE THREAD

**Issue by blockmood** [YGYOOO/ajax-interceptor#73]
计算数量接口可能5秒后才返回数量，插件拦截时机已经过了，因此拦截不到。

**Comment by YGYOOO** [comment]
你好，能否拦截到跟请求持续时间无关，跟请求触发时间有关，如果请求在该插件加载完成前触发，则拦截不到。
如果该接口可以手动触发（比如点击页面上某按钮触发），建议尝试一下，这样能拦截到。
