### ISSUE TITLE
使用了ajax-proxy后，开启插件后 请求无法resolve

### ISSUE THREAD

**Issue by le0l1** [YGYOOO/ajax-interceptor#81]
项目使用了ajax-hook,会对XMLHttpRequest进行劫持
正常情况下不开启插件情况下，请求的promise能够正常resolve
开启插件后,请求的promise无法正常resolve

---

原因:  
原生的XMLHttpRequest, 在实例化的过程中, 属性中存在 `onreadystatechange` 和 `onload` 两个函数，ajax-hook会对其进行代理
开启插件后，`myXHR` 会丢失上述两个函数，导致ajax-hook代理异常, 请求无法resolve

---

解决:
https://github.com/YGYOOO/ajax-interceptor/blob/7faaffee970afc4f9a33acfc2aa44ef67b7f9bd0/pageScripts/main.js#L36-L58

在上面的代码中，初始化`onreadystatechange`和`onload`两个函数

**Comment by YGYOOO** [comment]
#82
