### ISSUE TITLE
有的网站控制台会出现这个错误，点击菜单栏按钮没反应

### ISSUE THREAD

**Issue by ywlfff** [YGYOOO/ajax-interceptor#84]
网址为：https://xft.cmbchina.com
A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
![image](https://user-images.githubusercontent.com/32921822/195550976-107f31f7-d268-4151-9595-ae4a21a1bcc1.png)

**Comment by ywlfff** [comment]
算了

**Comment by YGYOOO** [comment]
已修复
