### ISSUE TITLE
add position setting

### ISSUE THREAD

**Issue by lxxorz** [YGYOOO/ajax-interceptor#96]
The panel is currently set to appear on the right side of the window by default, and it is hoped that position settings can be supported to prevent it from covering certain areas of the page.

**Comment by YGYOOO** [comment]
![image](https://github.com/YGYOOO/ajax-interceptor/assets/15754991/d448bd58-19a5-4dbf-8f9a-81d9de6cb52f)
![image](https://github.com/YGYOOO/ajax-interceptor/assets/15754991/1db01def-247c-4dcb-8f24-2817b2586759)
Please update to the new version 1.4.1 which could inject the panel into chrome devtools
