### ISSUE TITLE
修改代码后热更新

### ISSUE THREAD

**Issue by Gesj-yean** [YGYOOO/ajax-interceptor#98]
因为想要修改一个功能，请问大佬如何在修改 main.js 代码后热更新，不用手动 build 之后再刷新插件？

**Comment by YGYOOO** [comment]
![image](https://github.com/YGYOOO/ajax-interceptor/assets/15754991/656e5282-cdb1-4919-9b67-3e73c065821e)
我是通过webpack-dev-server单独跑起来，在浏览器中直接访问，就像你正常开发前端页面一样，只是这样只能调页面样式和交互，无法跟content.js、service_worker.js串起来，否则就得手动build。应该有更好的方法，还没研究

**Comment by Gesj-yean** [comment]
能运行起来了，感谢！
